version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "npm"
    directory: "/src/APIWeaver.Swagger"
    schedule:
      interval: "weekly"
      day: "monday"
