namespace APIWeaver.OpenApi.Tests;

public class StatusCodeExtensionsTests
{
    [Theory]
    [InlineData(StatusCodes.Status100Continue, "Continue")]
    [InlineData(StatusCodes.Status101SwitchingProtocols, "Switching Protocols")]
    [InlineData(StatusCodes.Status102Processing, "Processing")]
    [InlineData(StatusCodes.Status200OK, "OK")]
    [InlineData(StatusCodes.Status201Created, "Created")]
    [InlineData(StatusCodes.Status202Accepted, "Accepted")]
    [InlineData(StatusCodes.Status203NonAuthoritative, "Non-Authoritative Information")]
    [InlineData(StatusCodes.Status204NoContent, "No Content")]
    [InlineData(StatusCodes.Status205ResetContent, "Reset Content")]
    [InlineData(StatusCodes.Status206PartialContent, "Partial Content")]
    [InlineData(StatusCodes.Status300MultipleChoices, "Multiple Choices")]
    [InlineData(StatusCodes.Status301MovedPermanently, "Moved Permanently")]
    [InlineData(StatusCodes.Status302Found, "Found")]
    [InlineData(StatusCodes.Status303SeeOther, "See Other")]
    [InlineData(StatusCodes.Status304NotModified, "Not Modified")]
    [InlineData(StatusCodes.Status305UseProxy, "Use Proxy")]
    [InlineData(StatusCodes.Status307TemporaryRedirect, "Temporary Redirect")]
    [InlineData(StatusCodes.Status308PermanentRedirect, "Permanent Redirect")]
    [InlineData(StatusCodes.Status400BadRequest, "Bad Request")]
    [InlineData(StatusCodes.Status401Unauthorized, "Unauthorized")]
    [InlineData(StatusCodes.Status402PaymentRequired, "Payment Required")]
    [InlineData(StatusCodes.Status403Forbidden, "Forbidden")]
    [InlineData(StatusCodes.Status404NotFound, "Not Found")]
    [InlineData(StatusCodes.Status405MethodNotAllowed, "Method Not Allowed")]
    [InlineData(StatusCodes.Status406NotAcceptable, "Not Acceptable")]
    [InlineData(StatusCodes.Status407ProxyAuthenticationRequired, "Proxy Authentication Required")]
    [InlineData(StatusCodes.Status408RequestTimeout, "Request Timeout")]
    [InlineData(StatusCodes.Status409Conflict, "Conflict")]
    [InlineData(StatusCodes.Status410Gone, "Gone")]
    [InlineData(StatusCodes.Status411LengthRequired, "Length Required")]
    [InlineData(StatusCodes.Status412PreconditionFailed, "Precondition Failed")]
    [InlineData(StatusCodes.Status413PayloadTooLarge, "Payload Too Large")]
    [InlineData(StatusCodes.Status414UriTooLong, "URI Too Long")]
    [InlineData(StatusCodes.Status415UnsupportedMediaType, "Unsupported Media Type")]
    [InlineData(StatusCodes.Status416RangeNotSatisfiable, "Range Not Satisfiable")]
    [InlineData(StatusCodes.Status417ExpectationFailed, "Expectation Failed")]
    [InlineData(StatusCodes.Status418ImATeapot, "I'm a teapot")]
    [InlineData(StatusCodes.Status422UnprocessableEntity, "Unprocessable Entity")]
    [InlineData(StatusCodes.Status423Locked, "Locked")]
    [InlineData(StatusCodes.Status424FailedDependency, "Failed Dependency")]
    [InlineData(StatusCodes.Status426UpgradeRequired, "Upgrade Required")]
    [InlineData(StatusCodes.Status428PreconditionRequired, "Precondition Required")]
    [InlineData(StatusCodes.Status429TooManyRequests, "Too Many Requests")]
    [InlineData(StatusCodes.Status431RequestHeaderFieldsTooLarge, "Request Header Fields Too Large")]
    [InlineData(StatusCodes.Status451UnavailableForLegalReasons, "Unavailable For Legal Reasons")]
    [InlineData(StatusCodes.Status500InternalServerError, "Internal Server Error")]
    [InlineData(StatusCodes.Status501NotImplemented, "Not Implemented")]
    [InlineData(StatusCodes.Status502BadGateway, "Bad Gateway")]
    [InlineData(StatusCodes.Status503ServiceUnavailable, "Service Unavailable")]
    [InlineData(StatusCodes.Status504GatewayTimeout, "Gateway Timeout")]
    [InlineData(StatusCodes.Status505HttpVersionNotsupported, "HTTP Version Not Supported")]
    [InlineData(StatusCodes.Status506VariantAlsoNegotiates, "Variant Also Negotiates")]
    [InlineData(StatusCodes.Status507InsufficientStorage, "Insufficient Storage")]
    [InlineData(StatusCodes.Status508LoopDetected, "Loop Detected")]
    [InlineData(StatusCodes.Status510NotExtended, "Not Extended")]
    [InlineData(StatusCodes.Status511NetworkAuthenticationRequired, "Network Authentication Required")]
    [InlineData(999, "Unknown Status Code")]
    public void GetDescription_ShouldReturnExpectedDescription(int statusCode, string expectedDescription)
    {
        // Act
        var actualDescription = statusCode.GetDescription();

        // Assert
        actualDescription.Should().Be(expectedDescription);
    }
}