//----------------------
// <auto-generated>
//     Generated by APIWeaver.Generator
// </auto-generated>
//----------------------

using System.Text.Json.Serialization.Metadata;

namespace APIWeaver.Demo.GeneratedClient;

#nullable enable

public sealed class BookApiClient
{
    public async Task<Response<TOk, TNotFound, TConflict, TInternalServerError>> GetBookAsync<TOk, TNotFound, TConflict, TInternalServerError>(JsonTypeInfo<TOk> typeInfoOk, JsonTypeInfo<TNotFound> typeInfoNotFound, JsonTypeInfo<TConflict> typeInfoConflict, JsonTypeInfo<TInternalServerError> typeInfoInternalServerError, CancellationToken cancellationToken = default)
    {
        using var request = new HttpRequestMessage();
        await Task.CompletedTask;
        return default!;
    }
}

