//----------------------
// <auto-generated>
//     Generated by APIWeaver.Generator
// </auto-generated>
//----------------------

using System.Net;

namespace APIWeaver.Demo.GeneratedClient;

#nullable enable

public readonly struct Response<TOk>
{
    public bool IsSuccess => (int) StatusCode is >= 200 and <= 299;

    public required HttpStatusCode StatusCode { get; init; }

    public TOk? Ok { get; init; }

    public Stream? BodyStream { get; init; }
}


public readonly struct Response<TCreated, TConflict>
{
    public bool IsSuccess => (int) StatusCode is >= 200 and <= 299;

    public required HttpStatusCode StatusCode { get; init; }

    public TCreated? Created { get; init; }

    public TConflict? Conflict { get; init; }

    public Stream? BodyStream { get; init; }
}

