//----------------------
// <auto-generated>
//     Generated by APIWeaver.Generator
// </auto-generated>
//----------------------

using System.Text.Json.Serialization.Metadata;

namespace APIWeaver.Demo.GeneratedClient;

#nullable enable

public sealed class UserApiClient
{
    public async Task<Response<TOk, TNotFound>> GetUserByIdAsync<TOk, TNotFound>(JsonTypeInfo<TOk> typeInfoOk, JsonTypeInfo<TNotFound> typeInfoNotFound, CancellationToken cancellationToken = default)
    {
        using var request = new HttpRequestMessage();
        await Task.CompletedTask;
        return default!;
    }

    public async Task<Response<TOk, TNotFound>> GetUserAsync<TOk, TNotFound>(JsonTypeInfo<TOk> typeInfoOk, JsonTypeInfo<TNotFound> typeInfoNotFound, CancellationToken cancellationToken = default)
    {
        using var request = new HttpRequestMessage();
        await Task.CompletedTask;
        return default!;
    }
}

