name: Publish

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NODE_MODULES_PATH: 'src/APIWeaver.Swagger/node_modules'

jobs:
  node-setup:
    uses: xC0dex/APIWeaver/.github/workflows/node-assets.yml@main
  publish:
    runs-on: ubuntu-latest
    needs: 
      - node-setup
    strategy:
      matrix:
        project:
#          - 'APIWeaver.Core'
#          - 'APIWeaver.OpenApi'
#          - 'APIWeaver.Schema'
          - 'APIWeaver.Swagger'
    steps:
      - uses: actions/checkout@v4
      - name: Download Node.js modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: ${{ env.NODE_MODULES_PATH }}
      - name: Get version
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Pack ${{ matrix.project }}
        working-directory: src/${{ matrix.project }}
        run: dotnet pack -c Release --output nupkgs /p:Version=$VERSION /p:PackageVersion=$VERSION
      - name: Publish ${{ matrix.project }}
        working-directory: src/${{ matrix.project }}
        run: |
          dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push nupkgs/*.snupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate
