name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
#  publish-generator:
#    uses: xC0dex/APIWeaver/.github/workflows/publish-generator.yml@main
  publish:
    runs-on: ubuntu-latest
#    needs:
#      - publish-generator
    strategy:
      matrix:
        project:
#          - 'APIWeaver'
          - 'APIWeaver.OpenApi'
#          - 'APIWeaver.Swagger'
#          - 'APIWeaver.MsBuild'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Download APIWeaver.Generator
#        if: ${{ matrix.project }} == 'APIWeaver.MsBuild'
#        uses: actions/download-artifact@v4
#        with:
#          pattern: generator-*

      - name: Get version
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        working-directory: src/${{ matrix.project }}
        run: dotnet restore

      - name: Pack ${{ matrix.project }}
        working-directory: src/${{ matrix.project }}
        run: dotnet pack -c Release --no-restore --output nupkgs /p:Version=$VERSION

      - name: Publish ${{ matrix.project }}
        working-directory: src/${{ matrix.project }}
        run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
